# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createPNG <- function(mat, toFilename) {
    invisible(.Call(`_libattopng_createPNG`, mat, toFilename))
}

intToRGBA <- function(a1) {
    .Call(`_libattopng_intToRGBA`, a1)
}

convertFloat <- function(a1) {
    .Call(`_libattopng_convertFloat`, a1)
}

